---
# tasks file for multiple_remote_shell_script
# tasks file for remote_shell_script
- name: Gather Facts the hostname/fqdn
  setup:
    filter: ansible_fqdn    

- name: Fetch the current system timestamp
  local_action:
    module: shell
    _raw_params: date --utc +%Y%m%dT%H%M%S
  register: fetch_timestamp_result
  run_once: yes

- name: setup the current system timestamp
  set_fact:
    fetch_timestamp: "{{ fetch_timestamp_result.stdout }}"
    
- name: Loop to run script for multiple shell scripts
  include: run_script.yml
  with_items: "{{ shell_script }}"

